### ISSUE TITLE
So many bugs!!!

### ISSUE THREAD

**Issue by jianjuan** [Runinho/pytorch-cutpaste#1]
Is this your preliminary version? I tried to run code on the MVTec-AD, and there are so many bugs, do you have a specific pytorch version? There are unexpected parameters in dataloader. Although, these are small bugs, I have solved these and run it successfully.  Hope you to accomplish it!
Thank you!

**Comment by Runinho** [comment]
Yes this is a **unoffical** and preliminary version. I have only implemented the *normal* cutpaste augmentation and not the *scar* variation.
I tested the code with the latest PyTorch version 1.8.

Feel free to create a pull request with your bug fixes.

**Comment by Runinho** [comment]
I close this issue due to inactivity.
