### ISSUE TITLE
How to get the patch heatmap when evaluating？

### ISSUE THREAD

**Issue by hahahaha-hash** [Runinho/pytorch-cutpaste#17]
Thank you for your great effort of the codes. During the evaluation phase, there are only roc_plot and TSNE results in the eval folder. How can I get the patch heatmap  of defect images.

**Comment by Runinho** [comment]
The code currently does not support the generation of a heatmap.
Maybe I will find some time in the upcoming days to release some prototype code.

I will close this issue as a duplicate of #11
