### ISSUE TITLE
why loaded 0 images?

### ISSUE THREAD

**Issue by zj0118** [Runinho/pytorch-cutpaste#24]
![023c3c90e6e89b430179bae9c9c916d](https://user-images.githubusercontent.com/64900013/222061297-8c9aaf37-e68a-4143-a38e-5ef80c3bc0c2.png)
![b84e89023e88025766d44aad31e23d9](https://user-images.githubusercontent.com/64900013/222061347-59114d5d-60b2-4773-a90c-764159894511.png)
What should I do next?Please!

**Comment by Runinho** [comment]
Have you downloaded the dataset?

To quote the readme: 
> Download the MVTec Anomaly detection Dataset from [here](https://www.mvtec.com/company/research/datasets/mvtec-ad) and extract it into a new folder named `Data`.

**Comment by zj0118** [comment]
> Have you downloaded the dataset?
> 
> To quote the readme:
> 
> > Download the MVTec Anomaly detection Dataset from [here](https://www.mvtec.com/company/research/datasets/mvtec-ad) and extract it into a new folder named `Data`.

Thank you!
