### ISSUE TITLE
Change number of workers.

### ISSUE THREAD

**Issue by danielsoy** [Runinho/pytorch-cutpaste#26]
Hey!

Got this warning:
UserWarning: This DataLoader will create 8 worker processes in total

I need to reduce the number of workers from 8, to 4.

How do i change this variable in run_training.py?

Thanks!

**Comment by Runinho** [comment]
You can use the `--workers` argument:
```
python run_training.py --model_dir models --head_layer 2 --cuda 1 --workers 4
```

Or hardcode it [here](https://github.com/Runinho/pytorch-cutpaste/blob/3f2f55393d8d6e3e4395d557ab3a88267b6d99ad/run_training.py#L263):
```
workers=4)
```

**Comment by danielsoy** [comment]
Thanks!
