### ISSUE TITLE
--no-pretrained ?

### ISSUE THREAD

**Issue by danielsoy** [Runinho/pytorch-cutpaste#27]
what  does the argument  **--no-pretrained** mean, please?
 
does it train a model from scratch, or is it a kind of transfer learning?

can I use --no-pretrained arg, training with CPU, instead of GPU?

**Comment by Runinho** [comment]
> what  does the argument  **--no-pretrained** mean, please?
Check out `Python run_training.py --help` to get a small description for each parameter. 
> does it train a model from scratch, or is it a kind of transfer learning?
If `--no-pretrained` is set the model weights of the resnet18 will be randomly initialized. If it is not set the pretrained weights that come with pytorch are used. The relevant line in the code is [this one](https://github.com/Runinho/pytorch-cutpaste/blob/3f2f55393d8d6e3e4395d557ab3a88267b6d99ad/model.py#L11)
> 
> 
> can I use --no-pretrained arg, training with CPU, instead of GPU?
Should work. Just include `--cuda 0` in your arguments.

**Comment by danielsoy** [comment]
Great!
